package com.model;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "ARTICLE")
public class Article implements java.io.Serializable {

	private long id;
	private String nom;
	private String descrition;
	private long nsalle;
	private byte[] image;

	public Article() {
	}

	public Article(long id, String nom, long nsalle) {
		this.id = id;
		this.nom = nom;
		this.nsalle = nsalle;
	}

	public Article(long id, String nom, String descrition, long nsalle, byte[] image) {
		this.id = id;
		this.nom = nom;
		this.descrition = descrition;
		this.nsalle = nsalle;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="id_sequence")
	@SequenceGenerator(name="id_sequence", sequenceName="GM_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NOM", nullable = false, length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "DESCRITION", length = 300)
	public String getDescrition() {
		return this.descrition;
	}

	public void setDescrition(String descrition) {
		this.descrition = descrition;
	}

	@Column(name = "NSALLE", nullable = false, precision = 22, scale = 0)
	public long getNsalle() {
		return this.nsalle;
	}

	public void setNsalle(long nsalle) {
		this.nsalle = nsalle;
	}

	@Column(name = "IMAGE")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
