package com.model;
// Generated Mar 29, 2018 2:10:52 PM by Hibernate Tools 4.0.1.Final



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Personnel generated by hbm2java
 */
@Entity
@Table(name = "PERSONNEL")
public class Personnel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String nom;
	private String prenom;
	private String poste;
	private long salaire;

	public Personnel() {
	}

	public Personnel(long id, String nom, String prenom, String poste, long salaire) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.poste = poste;
		this.salaire = salaire;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="id_sequence")
	@SequenceGenerator(name="id_sequence", sequenceName="GM_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NOM", nullable = false, length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM", nullable = false, length = 20)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "POSTE", nullable = false, length = 20)
	public String getPoste() {
		return this.poste;
	}

	public void setPoste(String poste) {
		this.poste = poste;
	}

	@Column(name = "SALAIRE", nullable = false, precision = 22, scale = 0)
	public long getSalaire() {
		return this.salaire;
	}

	public void setSalaire(long salaire) {
		this.salaire = salaire;
	}

}
